# POST http://localhost:3003/api/users
# Content-Type: application/json

# {
# 	"name": "Thivagar",
# 	"username": "root",
# 	"password": "pass"
# }

# POST http://localhost:3003/api/login
# Content-Type: application/json

# {
# 	"username": "root",
# 	"password": "pass"
# }

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVlZjRiZDAwZDNiNDYxMWQ4ZTQ2MTIyYiIsImlhdCI6MTU5MzA5OTI2OH0.U4wiwfe7H48Hpn-8prDzcUZIid8v2R278uDfifsPb6M

{
	"title": "React patterns",
	"author": "Michael Chan",
	"url": "https://reactpatterns.com/",
	"likes": 7
}